### PR TITLE
Update README and update note for path

### PR DESCRIPTION
**Pull request by jingnan4k**

### CODE REVIEW

**Comment by Yuvania** [comment]
@jingnan4k Hello, I think it could be grammatically improved if the message was like this: 
Depending on your system, you must add the above paths to `~/.profile`, `~/. bash_profile`, or `~/. zshrc`.

**Comment by heatherwoz** [comment]
@jingnan4k I agree with @Yuvania . Her phrasing is more clear.

**Review by heatherwoz — CHANGES_REQUESTED** [review]
Rephrase for better grammar and clarity

**Comment by Yuvania** [comment]
@heatherwoz I already applied the change, can you merge it?

**Review by heatherwoz — APPROVED** [review]
Looks good

**Pull request merged**
