### PR TITLE
Removed --column-statistics which is only compatible with some versio…

### LINKED ISSUE #22: --column-statistics flag is only available in MySQL 8, but not modern versions of MariaDB
Causes this error:

```
pantheon-db-dump cepf-d7 dev | lando mysql
--Now waking up the server.--
 [notice] OK >> dev-cepf-d7.pantheonsite.io responded
--Now opening the SSH connection.--
--Now transferring the database.--
mysqldump: unknown variable 'column-statistics=0'
--Now cleaning up the SSH connection.--
All done
```

Using
```
mysqldump --version
mysqldump from 11.1.2-MariaDB, client 10.19 for osx10.18 (arm64)
```

This flag was added to try and make dumps faster.  So the fix is just to remove it.

### PR DESCRIPTION
**Pull request by dalin-**
Fixes #22

### CODE REVIEW

**Comment by unklCharlos** [comment]
@dalin- I started looking in to this but realized this command is not working for me at all. I get this result with and with out this fix whether I pipe it or not. Doesn't work for me on any environment/site. My local must be wonky?

```
pantheon-db-dump cepf-d7 dev | lando mysql 
--Now waking up the server.--
 [notice] OK >> dev-cepf-d7.pantheonsite.io responded
--Now opening the SSH connection.--
--Now transferring the database.--
mysqldump: [Warning] Using a password on the command line interface can be insecure.
mysqldump: Got errno 0 on write
--Now cleaning up the SSH connection.--
All done
```

Probably something to do with my mysqldump version:
```
mysqldump --version 
mysqldump  Ver 8.0.32 for macos12.6 on arm64 (Homebrew)
```
I can look in to changing my version and trying agian.

**Comment by dalin-** [comment]
> I get this result with and with out this fix

Sounds like your problem is unrelated. 

> mysqldump: Got errno 0 on write

It gets an error when it tries to write.  So maybe your problem is with the `lando mysql` part of the command.  🤷 

You could edit the script and right before the line that's being changed, echo out the full command
```sh
echo "mysqldump --no-autocommit --single-transaction -B --opt --quote-names --user=$mysql_username --host=127.0.0.1 --port=$mysql_port --password=$mysql_password $mysql_database | $PV"
```

Then whatever is echoed, copy it and run it in the terminal.  

This is basically how I debug all of these scripts.

**Comment by unklCharlos** [comment]
@dalin- I got my issue sorted out. Turns out I needed [pipe viewer](https://www.ivarch.com/programs/pv.shtml) installed since we are passing the progress of the download through to the command.

[I created a new issue for this.](https://github.com/fourkitchens/pantheon-tools/issues/26)

Unfortunately though with the --column-statistics removed for:
```
mysqldump --version 
mysqldump  Ver 8.0.32 for macos12.6 on arm64 (Homebrew)
```
I get:
```
mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_EXTRACT(HISTOGRAM, '$."number-of-buckets-specified"')                FROM information_schema.COLUMN_STATISTICS                WHERE SCHEMA_NAME = 'pantheon' AND TABLE_NAME = '_pantheon_heartbeat';': Unknown table 'COLUMN_STATISTICS' in information_schema (1109)
0:00:01 [1007  B/s] [>

```
Which the solution is to add it back :/

I installed mariadb (which I should probably be using anyway) and now I am able to run the command without error.

So approved but what if others are using mysql and not mariadb?

Also there is a comment on [line 46](https://github.com/fourkitchens/pantheon-tools/pull/23/files#diff-8897e441b7c09e987993f4a364a1f8f04f9e6c2af3da47bcf6941034ae5787e8R46) that looks like it was for debugging that could be removed. Not critical.

**Review by unklCharlos — APPROVED** [review]
Tested and approved!

**Comment by dalin-** [comment]
> what if others are using mysql and not mariadb?

I surprised/frustrated that the two can't use the same commandline arguments anymore.  

But as the POTS and Fire projects becomes more full-featured, pantheon-tools becomes less relevant.  The only site that we really _must_ use it for is ACLU since it's got some extra layers of security on top of it that make it difficult to use other methods to connect to the DB.

**Pull request merged**
