### PR TITLE
fix(16): Gracefully handle when Pantheon doesn't tell us the name of the DB

### LINKED ISSUE #16: 'pantheon-db-*' are suddenly failing because Pantheon is not reporting the name of the database
These commands rely on `terminus connection:info` to get data about the database.  But it's no longer returning the name of the DB:

```
➜ terminus connection:info columbia-sps.live  --format=print-r --fields='*'
Array
(
    [sftp_command] => sftp -o Port=2222 live.6170880e-6b27-46d1-910d-1a83c0d99b98@appserver.live.6170880e-6b27-46d1-910d-1a83c0d99b98.drush.in
    [sftp_username] => live.6170880e-6b27-46d1-910d-1a83c0d99b98
    [sftp_host] => appserver.live.6170880e-6b27-46d1-910d-1a83c0d99b98.drush.in
    [sftp_password] => Use your account password
    [sftp_url] => sftp://live.6170880e-6b27-46d1-910d-1a83c0d99b98@appserver.live.6170880e-6b27-46d1-910d-1a83c0d99b98.drush.in:2222
    [mysql_command] => mysql -u 41d1045d98ac4e02b6407d0106405b5a -p0e776c3d27204e54bc43ec1b52218d0d -h dbserver.live.6170880e-6b27-46d1-910d-1a83c0d99b98.drush.in -P 14960
    [mysql_username] => 41d1045d98ac4e02b6407d0106405b5a
    [mysql_host] => dbserver.live.6170880e-6b27-46d1-910d-1a83c0d99b98.drush.in
    [mysql_password] => 0e776c3d27204e54bc43ec1b52218d0d
    [mysql_url] => mysql://41d1045d98ac4e02b6407d0106405b5a:0e776c3d27204e54bc43ec1b52218d0d@dbserver.live.6170880e-6b27-46d1-910d-1a83c0d99b98.drush.in:14960/
    [mysql_port] => 14960
    [mysql_database] =>
    [redis_command] => redis-cli -h 34.135.30.224 -p 11255 -a 4c631bebe31e44abbfd94869e4b0ee0f
    [redis_port] => 11255
    [redis_url] => redis://b8603a26f0bd43cca513ad25bf146588:4c631bebe31e44abbfd94869e4b0ee0f@34.135.30.224:11255
    [redis_password] => 4c631bebe31e44abbfd94869e4b0ee0f
)
```

PR forthcoming to fallback to "pantheon" when this happens.

### PR DESCRIPTION
**Pull request by dalin-**
Running commands like 
```
pantheon-db-cli eam-d8 live
pantheon-db-dump columbia-sps test | gzip > columbia-sps.mysql.gzip
```
Will now work.

### CODE REVIEW

**Comment by unklCharlos** [comment]
@dalin- I keep getting `/pantheon-tools/pantheon-db-cli: line 45: mysql: command not found` when running `pantheon-db-cli eam-d8 live`

`pantheon-db-dump columbia-sps test | gzip > columbia-sps.mysql.gzip` worked great!

**Comment by dalin-** [comment]
@cbfannin 
That suggests that on your local machine you have the application `mysqldump`, but not `mysql`.  Is that correct?  If so, any idea how?  We might add checks at the top of these files to confirm that you have the required application installed, but that should be a different PR.

**Comment by unklCharlos** [comment]
@dalin- That probably explains my errors. I actually don't have `mysql` or `mysqldump` installed on my local machine. I've not had to do anything outside of lando for several months so haven't installed it.

On a Drupal build script I created at my previous employer my co-worker did a basic loop that checked multiple applications to see if they were installed. Maybe something like this will work?

```
# Functions
isInstalled() {
    # check if command exists and fail otherwise
    command -v "$1" >/dev/null 2>&1
    if [[ $? -ne 0 ]]; then
        echo "${white}${red} $1 is not installed. ${reset}${white}${red}"
        exit 1
    fi
}
echo "${white}${blue} Checking Prerequisites... ${reset}${white}${blue}"

# Check for required Applications.
for app in "php" "composer" "git" "docker" "lando" "curl"; do
    isInstalled "${app}"
done
```

**Comment by dalin-** [comment]
@cbfannin 
Yes.  Something like that.  Not sure if the loop is overkill since we only need to check for one application.  But let's do that as a separate PR.

**Review by unklCharlos — APPROVED** [review]
code looks good. After installing mysql locally both commands worked as expected. Ready to merge!

**Pull request merged**
